CREATE TABLE studiokeeper_catalog (
        user_id INTEGER REFERENCES studiokeeper_users(id),
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        type TEXT NOT NULL,
        collection TEXT,
        name TEXT NOT NULL,
        size TEXT,
        medium TEXT,
        price DECIMAL(6,2),
        date_created DATE,
        concept_statement TEXT,
        notes TEXT,
        images TEXT,
        subject TEXT,
        quantity SMALLINT,
        location TEXT,
        sold_date DATE,
        sold_to TEXT,
        history TEXT
);


