CREATE TABLE studiokeeper_contacts (
    user_id INTEGER REFERENCES studiokeeper_users (id),
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    contact_type TEXT,
    business_name VARCHAR(50),
    name VARCHAR(50),
    title VARCHAR(50),
    email VARCHAR(50),
    phone VARCHAR(50),
    address_street TEXT,
    address_line2 TEXT,
    address_city TEXT, 
    address_state TEXT,
    address_zip INTEGER,
    address_country TEXT,
    website TEXT,
    notes TEXT
);
