CREATE TABLE studiokeeper_events (
    user_id INTEGER REFERENCES studiokeeper_users (id),
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    event_type TEXT,
    name TEXT NOT NULL,
    website TEXT,
    location TEXT,
    event_dates DATE,
    application_due_date DATE,
    notes TEXT,
    submission_requirements TEXT
)