create TABLE studiokeeper_catalog_contacts_favorites
(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        catalog_id INTEGER REFERENCES studiokeeper_catalog (id) NOT NULL,
        contact_id INTEGER REFERENCES studiokeeper_contacts (id) NOT NULL
);