create TABLE studiokeeper_catalog_events_connection
(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        catalog_id INTEGER REFERENCES studiokeeper_catalog (id) NOT NULL,
        event_id INTEGER REFERENCES studiokeeper_events (id) NOT NULL
);