
create TABLE studiokeeper_contacts_events_relationship
(
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        contact_id INTEGER REFERENCES studiokeeper_contacts (id) NOT NULL,
        event_id INTEGER REFERENCES studiokeeper_events (id) NOT NULL
);