CREATE TABLE studiokeeper_images 
(    
        user_id INTEGER REFERENCES studiokeeper_users(id),
        id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
        image_name TEXT NOT NULL,
        catalog_id INTEGER REFERENCES studiokeeper_catalog (id) NOT NULL     
);


